### ISSUE TITLE
Alterar o repositório de documentos para o drive

### ISSUE THREAD

**Issue by Eddyosos** [gpr-adriana/documents#102]
Sugiro ao @josimarMorais (GCO) que mude o repositório (só os arquivos, não as tarefas) para o google drive/dropbox
# Motivos:
1. É mais fácil e produtivo de usar
2. A configuração pode ser separada individualmente
3. Os links não quebram
4. É versionado (também)
5. Se alinha melhor com o que a Adriana quer (alterações são imediatas)

**Comment by josimarMorais** [comment]
Alteração aceita.
