### ISSUE TITLE
Sugestão de métricas

### ISSUE THREAD

**Issue by Eddyosos** [gpr-adriana/documents#106]
# Métricas
## Tempo comprometido a sprint

A quantidade que cada membro colocou na tabela de tempo semanal de trabalho
Sendo coletado imediatamente antes do Sprint Planning
## Tempo dedicado a sprint

A soma da quantidade de horas de cada membro na sprint
Sendo coletado imediatamente antes de cada Sprint retrospective ( a presença no sprint retrospective é somada na próxima coleta)
## Engajamento

O percentual das presenças em reuniões
Sendo coletado imediatamente antes de cada Sprint retrospective ( a presença no sprint retrospective é somada na próxima coleta) 
## Dias impedidos

A quantidade de dias que foram perdidos por quaisquer impedimentos durante a sprint
Sendo coletada imediatamente antes de cada Sprint retrospective

**Comment by caioromao** [comment]
Aprovadas sugestões de métricas aqui descritas.
