### ISSUE TITLE
Não-conformidade GPR

### ISSUE THREAD

**Issue by eliezerdejj** [gpr-adriana/documents#110]
colocar sua planilha de avaliação junto com as demais, foi definido que as planilhas de avaliação ficariam na pasta do projeto, junto com as demais

**Comment by caioromao** [comment]
Ok, de acordo. Farei isso e assim que finalizar insiro um comentário aqui.

**Comment by caioromao** [comment]
Pronto. Foi feito o "merge". Planilha de avaliação encontra-se junto com as outras.
