### ISSUE TITLE
não-conformidade GPR

### ISSUE THREAD

**Issue by eliezerdejj** [gpr-adriana/documents#111]
Onde posso encontrar os artefatos que você está indicando na planilha?? Por favor indique onde está os itens se são no github ou no drive, foi combinado que tudo estaria no drive, isso é necessário pelo fato de que alguns artefatos voce criou, ou deixou os mesmos das sprints passadas, por isso preciso saber onde encontram, e se você irá coloca-los no drive

**Comment by caioromao** [comment]
Grande parte dos artefatos encontra-se no Github. Inclusive ha hiperlinks que direcionam exatamente para o local desejado. Não pretendia colocar nenhum no Drive, mas posso colocar caso haja necessidade.
