### ISSUE TITLE
Regras de Negócios dos Crud  de Médico

### ISSUE THREAD

**Issue by josimarMorais** [gpr-adriana/documents#18]
- Um médico pode ter mais de uma especialidade
- Um médico contém um CRM – (Conselho Regional dos Médicos) que é formado somente por números seguido da Sigla do Estado ex: 0000/GO minímo 4 dígitos ou no máximo 10 dígitos
- Um médico pode ter mais de um e-mail cadastrado.

**Comment by Eddyosos** [comment]
Deveria estar no quadro development, repassado
