### ISSUE TITLE
Lista de todos os Médicos do hospital

### ISSUE THREAD

**Issue by josimarMorais** [gpr-adriana/documents#22]
Na página inicial, para qualquer tipo de usuário, deve haver um direcionador com uma lista que apresente todos os médicos do hospital

**Comment by josimarMorais** [comment]
Na página inicial, para qualquer tipo de usuário, deve haver um direcionador com uma lista que apresente todos os médicos do hospital.

**Comment by Eddyosos** [comment]
Deveria estar no quadro development, não foi especificado o requisito ou não existem
