### ISSUE TITLE
Revisar os requisitos [due:25/05]

### ISSUE THREAD

**Issue by Eddyosos** [gpr-adriana/documents#24]
Revisar os requisitos propostos no quadro development

**Comment by caioromao** [comment]
Requisitos em revisão junto com o Gerente de Requisitos.

**Comment by Eddyosos** [comment]
Vi que vocês estão trabalhando nisso, lembrando que isso pode impactar no desenvolvimento, deem prioridade de revisão para as tarefas que estão em andamento e que tem data de entrega próxima
@caioromao @josimarMorais

**Comment by caioromao** [comment]
Requisitos revisados e validados junto com o Gerente de Requisitos.
