### ISSUE TITLE
Revisar Product backlog [due:24/05]

### ISSUE THREAD

**Issue by Eddyosos** [gpr-adriana/documents#5]
Revisar se o product backlog foi passado corretamente para o zube

**Comment by Eddyosos** [comment]
Olha a questão do gilmar na tarefa de médico também (id 18 development)

**Comment by caioromao** [comment]
O Product Backlog foi passado parcialmente para o Zube. Faltaram 4 estórias de usuário, que são:
ID 5
ID 6
ID 7
ID 8

*Em caso de dúvida, verificar Product Backlog no Google Drive

**Comment by caioromao** [comment]
Foi percebido que faltaram 4 estórias de usuário na exportação do Product Backlog para o Zube.
Entretanto, essas 4 estórias já foram entregues na Sprint 2. São elas:
ID 5
ID 6
ID 7
ID 8

As mesmas serão adicionadas na Sprint 2, no Zube.
De resto, exportação validada.

**Comment by caioromao** [comment]
Verificado e aprovado a exportação do Product Backlog para o Zube.
