### ISSUE TITLE
Sprint Review

### ISSUE THREAD

**Issue by Eddyosos** [gpr-adriana/documents#78]

**Comment by vinilopes03** [comment]
-Apresentação dos problemas da equipe durante a terceira Sprint.
-Discussão do que foi feito e o que não foi feito das atividades planejadas para a Sprint.
-Apresentação das atividades feitas durante a Sprint pela a equipe de desenvolvimento
-Parecer do Product Owner sobre as atividades realizadas pela equipe.
-Apresentar e solucionar as últimas duvidas da equipe.
