### ISSUE TITLE
SPRINT PLANNING pt1

### ISSUE THREAD

**Issue by Eddyosos** [gpr-adriana/documents#81]

**Comment by vinilopes03** [comment]
- Apresentar as sugestões para a próxima Sprint.
- Realizar o Planning Poker das atividades que entrarão para a próxima Sprint.

Triagem - 8 horas
Usuário - 8 horas
RN do CRUD dos médicos - 1 hora.

Observação: A continuação da Sprint Planning ficou definida para ser realizada no dia 10/06, pois ficou faltando especificações das demais atividades.
